sequenceDiagram
  participant participant_createRuntimeEventOperationBindingContext as createRuntimeEventOperationBindingContext
  participant participant_isRecord as isRecord
  participant_createRuntimeEventOperationBindingContext->>participant_isRecord: isRecord()
  participant_isRecord-->>participant_createRuntimeEventOperationBindingContext: return
