sequenceDiagram
  participant participant_use as use
  participant participant_useManifestContext as useManifestContext
  participant_useManifestContext->>participant_use: use()
  participant_use-->>participant_useManifestContext: return
