sequenceDiagram
  participant participant_use as use
  participant participant_useOptionalManifestContext as useOptionalManifestContext
  participant_useOptionalManifestContext->>participant_use: use()
  participant_use-->>participant_useOptionalManifestContext: return
