sequenceDiagram
  participant participant_useContext as useContext
  participant participant_useManifestContext as useManifestContext
  participant_useManifestContext->>participant_useContext: useContext()
  participant_useContext-->>participant_useManifestContext: return
