sequenceDiagram
  participant participant_use as use
  participant participant_useManifest as useManifest
  participant_useManifest->>participant_use: use()
  participant_use-->>participant_useManifest: return
