sequenceDiagram
  participant participant_use as use
  participant participant_useRuntimeRendererConfig as useRuntimeRendererConfig
  participant_useRuntimeRendererConfig->>participant_use: use()
  participant_use-->>participant_useRuntimeRendererConfig: return
