sequenceDiagram
  participant participant_createRuntimeBindingDiagnostic as createRuntimeBindingDiagnostic
  participant participant_resolveRuntimeBindingEndpoint as resolveRuntimeBindingEndpoint
  participant participant_validateRuntimeBindingOperationRef as validateRuntimeBindingOperationRef
  participant_validateRuntimeBindingOperationRef->>participant_createRuntimeBindingDiagnostic: createRuntimeBindingDiagnostic()
  participant_createRuntimeBindingDiagnostic-->>participant_validateRuntimeBindingOperationRef: return
  participant_validateRuntimeBindingOperationRef->>participant_resolveRuntimeBindingEndpoint: resolveRuntimeBindingEndpoint()
  participant_resolveRuntimeBindingEndpoint-->>participant_validateRuntimeBindingOperationRef: return
