sequenceDiagram
  participant participant_createApiDiagnostic as createApiDiagnostic
  participant participant_findRuntimeApi as findRuntimeApi
  participant participant_resolveRuntimeApiEndpoint as resolveRuntimeApiEndpoint
  participant participant_validateRuntimeBindingOperationRef as validateRuntimeBindingOperationRef
  participant_validateRuntimeBindingOperationRef->>participant_findRuntimeApi: findRuntimeApi()
  participant_findRuntimeApi-->>participant_validateRuntimeBindingOperationRef: return
  participant_validateRuntimeBindingOperationRef->>participant_createApiDiagnostic: createApiDiagnostic()
  participant_createApiDiagnostic-->>participant_validateRuntimeBindingOperationRef: return
  participant_validateRuntimeBindingOperationRef->>participant_resolveRuntimeApiEndpoint: resolveRuntimeApiEndpoint()
  participant_resolveRuntimeApiEndpoint-->>participant_validateRuntimeBindingOperationRef: return
